version: '3.8'
services:
  sisyphus-frontend:
    environment:
      - SISYPHUS_BACKEND_HOSTNAME=${SISYPHUS_BACKEND_HOSTNAME}
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    image: sisyphus-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
